#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_contact_index:
    path: /app_contact
    controller: App\Controller\ContactController::index
    methods: [GET, POST]
